# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mechanize-Plugin-Snapshot
version:      0.20
version_from: lib/WWW/Mechanize/Plugin/Snapshot.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Data::Dumper:                  0
    File::Path:                    0
    File::Spec:                    0
    Test::More:                    0
    Text::Template:                0
    WWW::Mechanize::Pluggable:     1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
